services:
    app.breadcrumb:
        class: StudentBundle\Service\Breadcrumb
        arguments:
            breadcrumbs: "@white_october_breadcrumbs"
            container: "@service_container"

    app.action:
        class: StudentBundle\Service\ActionService
        parent: app.base
