<?php

namespace StudentBundle\Repository;
/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActionAndStudent($name_action, $student_id)
    {
        return $this->createQueryBuilder('a')
            ->join('a.students', 's')
            ->where('s.id = :student')
            ->addSelect('s')
            ->andWhere('a.name = :nameAction')
            ->orderBy('a.id', 'DESC')
            ->setParameters(['student' => $student_id, 'nameAction' => $name_action])
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findLast($student_id)
    {
        return $this->createQueryBuilder('a')
            ->join('a.students', 's')
            ->where('s.id = :student')
            ->addSelect('s')
            ->setParameter('student', $student_id)
            ->orderBy('a.id', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleResult();

    }
}
