<?php

namespace StudentBundle\Repository;

/**
 * RetrieveTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetrieveTimeRepository extends \Doctrine\ORM\EntityRepository
{
}
