<?php

namespace StudentBundle\Repository;

/**
 * RetrieveTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetrieveTimeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRetrieveTime($student)
    {
        $startDate = date( 'Y-m-' ) . '01'; // First day in current month
        $endDate   = date( 'Y-m-t' ); // Last day in current month
        return $this->createQueryBuilder('r')
            ->join('r.students', 'stu')
            ->where('stu.id=:student')
            ->andWhere('r.date >= :startDate')
            ->andWhere('r.date <= :endDate')
            ->setParameters([
                'student' => $student->getId(),
                'startDate' => $startDate,
                'endDate' => $endDate
            ])
            ->getQuery()
            ->getResult();

    }
}
