<?php

namespace AppBundle\Repository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCourseBySection($id)
    {
        $qb = $this->createQueryBuilder('c');
        return $qb
            ->join('c.sections', 'sec')
            ->where('sec.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }

}
