<?php

namespace AppBundle\Repository;

/**
 * CourseCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
