<?php

namespace AppBundle\Repository;

/**
 * CourseCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCourseCategoryByCourse($id)
    {
        $qb = $this->createQueryBuilder('course_category');
        return $qb
            ->join('course_category.course', 'course')
            ->where('course.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }

    public function findCourseCategoryElement($id, $student_id)
    {
        $qb = $this->createQueryBuilder('cc');
        return $qb
            ->join('cc.docRelation', 'dr')
            ->where('dr.courseCategory = :id')
            ->addSelect('dr')
            ->join('dr.qcm', 'qcm')
            ->addSelect('qcm')
            ->join('qcm.score', 'score')
            ->addSelect('score')
            ->andWhere('score.student = :student_id')
            ->setParameters(["id" => $id, "student_id" => $student_id])
            ->getQuery()
            ->getSingleResult()
            ;
    }
}
