<?php

namespace AppBundle\Repository;

/**
 * CourseCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCourseCategoryByCourse($id)
    {
        $qb = $this->createQueryBuilder('course_category');
        return $qb
            ->join('course_category.course', 'course')
            ->where('course.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }
}
