# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    appbundle_logoutlistener:
        class: AppBundle\EventListener\LogoutListener
        arguments: ['@app.action', '@app.check_role', '@doctrine.orm.entity_manager', '@app.retrievetime']

    appbundle_loginlistener:
        class: AppBundle\EventListener\LoginListener
        arguments: ['@security.token_storage', '@doctrine.orm.entity_manager', '@app.check_role', '@app.retrievetime', '@app.action', '@twig', ]
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }



