# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public:    false
        arguments:
            - 'mysql:host=%database_host%;dbname=%database_name%'
            - { db_table: sessions, db_username: '%database_user%', db_password: '%database_password%' }

    appbundle_logoutlistener:
        class: AppBundle\EventListener\LogoutListener

