app_debug:
    path: /debug
    defaults: { _controller: AppBundle:Base:debug }

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Base:index }

app_register:
    path: /registers
    defaults: { _controller: AppBundle:Base:register}