app_supervisor_display:
    path: /supervisor
    defaults: { _controller: AppBundle:User:displaySupervisor }

app_user_create:
     path: /supervisor/create
     defaults: { _controller: AppBundle:User:create }
     options:
         expose: true

app_user_delete:
     path: /supervisor/delete/{id}
     defaults: { _controller: AppBundle:User:delete }
     requirements:
         id: '\d+'
     options:
         expose: true

app_user_edit:
    path: /supervisor/edit/{id}
    defaults: { _controller: AppBundle:User:edit }
    requirements:
        id: '\d+'
    options:
        expose: true

app_user_display:
    path: section/{id}/user
    defaults: { _controller: AppBundle:User:displayUsers }
    requirements:
        id: '\d+'