student_homepage:
    path:     /
    defaults: { _controller: StudentBundle:Base:index }

student_display_course:
    path: /cours/{id}
    defaults: { _controller: StudentBundle:Base:displayCourse }
    requirements:
        id: '\d+'

student_display_courseCategory:
    path: /cours/matiere/{id}
    defaults: { _controller: StudentBundle:Base:displayCourseCategory }
    requirements:
        id: '\d+'

student_set_act:
    path: /setAct
    defaults: { _controller: StudentBundle:Action:setStudentAct }
    options:
        expose: true

student_display_grade:
    path: /getGrades
    defaults: { _controller: StudentBundle:Base:displayGrades }
    options:
        expose: true