qcm_display_all:
    path:     /qcm
    defaults: { _controller: QcmBundle:Base:displayAll }

qcm_display_questions:
    path: /qcm/{id}
    requirements:
        id: '\d+'
    defaults: { _controller: QcmBundle:Base:displayQuestionOfQcm }

app_create_qcm:
    path: qcm/create
    defaults: { _controller: QcmBundle:Base:create }
    options:
        expose: true

app_delete_qcm:
    path: qcm/delete/{id}
    defaults: { _controller: QcmBundle:Base:delete }
    requirements:
            id: '\d+'
    options:
        expose: true

app_edit_qcm:
    path: qcm/edit/{id}
    defaults: { _controller: QcmBundle:Base:edit }
    requirements:
            id: '\d+'
    options:
        expose: true