base:
    resource: "@AppBundle/Resources/config/_routing/base.yml"

section:
    resource: "@AppBundle/Resources/config/_routing/section.yml"

document:
    resource: "@AppBundle/Resources/config/_routing/document.yml"

student:
    resource: "@AppBundle/Resources/config/_routing/student.yml"

supervisor:
    resource: "@AppBundle/Resources/config/_routing/supervisor.yml"

course:
    resource: "@AppBundle/Resources/config/_routing/course.yml"

courseCategory:
    resource: "@AppBundle/Resources/config/_routing/courseCategory.yml"

app.pdf:
    path: /pdf
    defaults: { _controller: AppBundle:TimeRetrieve:pdf}
