<?php

namespace QcmBundle\Repository;

/**
 * QcmAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QcmAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
