<?php

namespace QcmBundle\Repository;

/**
 * QcmQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QcmQuestionRepository extends \Doctrine\ORM\EntityRepository
{

}
