<?php

namespace QcmBundle\Repository;

/**
 * QcmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoreRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByQcm($qcm_id, $student_id)
    {
        return $this->createQueryBuilder('score')
            ->join('score.qcm', 'qcm')
            ->where('qcm.id = :qcm_id')
            ->andWhere('score.student = :student_id')
            ->setParameters(['qcm_id' => $qcm_id, 'student_id' => $student_id])
            ->orderBy('score.id', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
